name: Deploy Laravel to Shared Hosting (FTP Only)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          composer install --optimize-autoloader --no-dev

      # Upload source code (kecuali folder public dan .env) ke laravel-app
      - name: Upload source code to laravel-app folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./              # Upload seluruh folder project
          server-dir: /laravel-app   # Ganti dengan path folder program di server
          exclude: |
            public/*                 # Jangan upload folder public
            .env                     # Jangan upload file .env

      # Upload folder public ke public_html
      - name: Upload public files to public_html folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public        # Upload hanya folder public
          server-dir: /public_html   # Ganti dengan path folder public di server

      # Buat file .env dari GitHub Secrets dan upload ke server
      - name: Create and upload .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          curl -T .env ftp://${{ secrets.FTP_SERVER }}/laravel-app/.env --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}"
